Security ajust recaptcha
getheimdall/heimdall pull request #393
Opened 2021-01-04 22:23 UTC by LeticiaCLabs

Implementação do Captcha e Não exibição do hash de senha da página de Admin do Heimdall

2021-01-05 13:31 UTC, jeffersonxc22 commented on heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/AuthResource.java
> +        if(!accountCredentials.getCaptchaResponse().equals("false")){
you could  use  Boolean.FALSE.toString() and change the expression, it's not  clean.
try this.
Boolean.TRUE.toString().equals(accountCredentials.getCaptchaResponse())

2021-01-06 13:51 UTC, smrafael requested changes

2021-01-06 13:51 UTC, smrafael commented on heimdall-api/src/main/java/br/com/conductor/heimdall/api/resource/UserResource.java
> +          user.setPassword("hidden");
Put string "hidden" in a instancy final variable and reuse

2021-01-06 13:52 UTC, smrafael approved these changes

2021-01-06 14:01 UTC, merged